trigger:
- main

pool:
  name: 'Self-hosted Pool'  # Remplacez par le nom de votre pool d'agents auto-hébergé

variables:
  environmentUrl: 'https://dev.azure.com/TribunalAdministratifQuebec'
  solutionName: 'devopsTestSolution'
  exportPath: '$(Build.ArtifactStagingDirectory)/solution'
  gitUserName: 'julienWorkTaq'
  gitUserEmail: 'julien.veret@taq.gouv.qc.ca'

steps:
- script: |
    echo "Installing Power Platform CLI"
    npm install -g pac-cli
  displayName: 'Install Power Platform CLI'

- script: |
    echo "Setting up Git configuration"
    git config --global user.name "$(gitUserName)"
    git config --global user.email "$(gitUserEmail)"
  displayName: 'Configure Git'

- task: PowerShell@2
  inputs:
    filePath: 'S:/temp/scriptExecPowerShell/export-solution.ps1'
    arguments: '-environmentUrl "$(environmentUrl)" -solutionName "$(solutionName)" -exportPath "$(exportPath)"'
  displayName: 'Export Power Platform Solution'

- script: |
    echo "Running tests"
    # Ajoutez ici les commandes spécifiques pour exécuter vos tests
  displayName: 'Run Tests'

- script: |
    echo "Checking for changes"
    cd $(exportPath)
    if [ -n "$(git status --porcelain)" ]; then
      echo "Changes detected, committing and pushing"
      git add .
      git commit -m "Automated commit from Azure DevOps pipeline"
      git push origin main
    else
      echo "No changes to commit"
    fi
  displayName: 'Commit and Push Changes'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
